baseURL = "https://jimmyaldape.com/"
languageCode = "en-us"
title = "Jimmy Aldape | Full-Stack Developer"
theme = "hugo-freelancer-theme"
googleAnalytics = "UA-80604328-7"

[params]

    name = "Jimmy Aldape"
    description = "Jimmy Aldape is a full-stack developer based in Riverside, CA who has a passion for solving problems and making things for the web"
    keywords = "Jimmy Aldape, Jimmy, Aldape, jimmyaldape, software engineer, full-stack software engineer, full stack software engineer, front-end engineer, back-end engineer, full-stack developer, full stack developer, web developer, application developer, javascript, laravel, tailwindcss, california"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "me@jimmyaldape.com"

    # Custom assets
    custom_css = []
    custom_js  = []

    [params.navigation]
        brand = ""


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        profile = "ja_logo_letter_blank_white.png"
        image = "ja_logo_letter_blank_white.png"
        background = ""
        name = "Jimmy Aldape"
        subtitle = "Full-Stack Developer"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more information take a look at the README.
        title = "Portfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"

    [params.skills]

        title = "Skills"
        description = ""

        [[params.skills.items]]
            name = "PHP"

        [[params.skills.items]]
            name = "C#"

        [[params.skills.items]]
            name = "Javascript"

        [[params.skills.items]]
            name = "Laravel"

        [[params.skills.items]]
            name = "Vue"

        [[params.skills.items]]
            name = "Tailwind CSS"

        [[params.skills.items]]
            name = "React"

        [[params.skills.items]]
            name = "Node"

        [[params.skills.items]]
            name = "Hugo"

        [[params.skills.items]]
            name = "Netlify"

        [[params.skills.items]]
            name = "Webpack"

        [[params.skills.items]]
            name = "SQL"

    [params.about]
        title = "About"

        [params.about.center]
            top = "I'm a full-stack developer based in Riverside, CA who has a passion for solving problems and making things for the web. I love bringing ideas to life."
            bottom = "I love working with [Laravel](https://laravel.com/) and [Tailwind CSS](https://tailwindcss.com/)"

        [params.about.button]
            text = "Resume"
            link = "/pdf/jimmy_aldape_resume_current.pdf"
            icon = ""


    [params.contact]
        title = "Contact"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Built with [Netlify](https://www.netlify.com/), [Hugo](https://gohugo.io) and the [Freelancer](https://github.com/digitalcraftsman/hugo-freelancer-theme) theme"

        [params.footer.social]
            #title = "Around the web"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fa-github"
                link = "//github.com/jimmyaldape"

            [[params.footer.social.networks]]
            icon = "fa-linkedin"
            link = "//www.linkedin.com/in/jimmyaldape"

            [[params.footer.social.networks]]
            icon = "fa-twitter"
            link = "//www.twitter.com/jimmyaldape"
